#!/bin/sh
basedir=$(dirname $0)
cd "$basedir"
cd ..

dissertation="$1"

# Build the dissertation.
xelatex "$dissertation"
bibtex "$dissertation"
for f in chapters/*.tex; do bibtex "${f%.tex}"; done
xelatex "$dissertation"
xelatex "$dissertation"

# Don't hide the log.
#mv "$dissertation.log" ".logged"

# also build the extra poster page
pdflatex extra/tree-large
